# Generated by Django 5.1.5 on 2025-03-08 14:20

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Nom Client')),
                ('client_license_plate', models.CharField(max_length=20, verbose_name='Plaque')),
                ('client_vehicle_date', models.DateField(verbose_name='Mise en circulation')),
                ('commercial_advisor', models.CharField(max_length=100, verbose_name='Nom Commercial')),
                ('service_advisor', models.CharField(max_length=100, verbose_name='Nom conseiller de service')),
                ('criticality', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Critique')], max_length=20, verbose_name='Criticité')),
                ('reservation_date', models.DateField(verbose_name='Date de réservation')),
                ('reservation_duration', models.PositiveIntegerField(help_text='en jours', verbose_name='Durée de la réservation')),
                ('reasons', models.TextField()),
                ('is_assigned', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('driving_license_front', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('driving_license_back', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('id_card_front', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('id_card_back', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle')),
            ],
        ),
    ]
