# Generated by Django 5.1.5 on 2025-03-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status_validation',
            field=models.CharField(choices=[('pending', 'En attente de validation'), ('approved', 'Validée'), ('rejected', 'Rejetée')], default='pending', max_length=10, verbose_name='Statut de validation'),
        ),
    ]
