# Generated by Django 5.1.5 on 2025-03-10 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_status_validation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'permissions': [('can_validate_reservation', 'Peut valider les réservations')]},
        ),
    ]
