# Generated by Django 5.1.5 on 2025-03-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='Numéro de Châssis')),
                ('mileage', models.PositiveIntegerField()),
                ('availability', models.CharField(choices=[('disponible', 'Disponible'), ('réservé', 'Réservé'), ('indisponible', 'Indisponible')], default='disponible', max_length=15)),
                ('last_service_km', models.PositiveIntegerField()),
                ('fuel_level', models.PositiveIntegerField(default=50, verbose_name='Niveau de Carburant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
